
# Select_fields (List of Specific Fields to Include in tables)
spool_select_fields = ['Fab ID', 'NDE Group', 'Spool', 'Job', 'Spool/Piece Mark', 'Ref Drawing', 'Line ID', 'Series','Sheet','Drawing Rev.', 'Spool Rev.', 'Pipe Spec', 
                    'MAT. Group', 'NPS', 'PWHT', 'Paint System', 'Paint Color', 'Plant Area', 'Notes', 'Spool_Status', 'Voided'
                    ]

        
weld_select_fields = ['Weld Index', 'WLD_ID', 'Job', 'Spool', 'Weld Label','Weld ID', 'Revision', 'Size', 'Joint', 'Joint 2','Joint Detail', 
                      'SCH','SCH Desc.', 'MTRL Group', 'Pipe Spec', 'Material','DiaInch'] # Weld ID is Generated


spool_column_mapping = {
   'SP_ID': 'Fab ID',
   'Spool_ID': 'Spool',
   'Job_ID': 'Job', 
   'Spool_Rev': 'Spool Rev.',
   'PC_Mark': 'Spool/Piece Mark',
   'Ref_Drg': 'Ref Drawing',
   'Ref_Rev': 'Drawing Rev.',
   'Client_Release_No': 'Client Release Number',
   'System': 'System',
   'Service': 'Service Type',
   'Transmittal_Cl': 'Client Transmittal',
   'ISO_Received': 'ISO Received Date',
   'Contractual_FRD': 'Contractual FRD',
   'Client_Target_FRD': 'Client Target FRD',
   'Schedule': 'Schedule',
   'Spec': 'Pipe Spec',
   'Mat_Group': 'MAT. Group',
   'NPS': 'NPS',
   'LBs': 'Weight (lbs)',
   'Surface_Area': 'Surface Area',
   'FDI': 'Field Design Input',
   'Priority': 'Priority',
   'PWHT': 'PWHT',
   'Paint_Sys': 'Paint System',
   'PaintColor': 'Paint Color',
   'Plant_Area': 'Plant Area',
   'Hydro': 'Hydro Test',
   'DR': 'Dimensional Report',
   'On_Hold': 'Hold Date',
   'Off_Hold': 'Hold Release Date', 
   'Hold_Code': 'Hold Code',
   'Hold_Desc': 'Hold Description',
   'drawn_by': 'Drawn By',
   'Drawn': 'Drawn',
   'Eng_Rel': 'Eng Rel',
   'MC_Rel': 'MC Rel',
   'Cut': 'Cut',
   'First_Fit': 'First Fit',
   'Final_Fit': 'Final Fit',
   'WeldOut': 'Weld Out',
   'Check_Out': 'Check Out',
   'QC': 'QC',
   'NDE': 'NDE',
   'InHydro': 'In Hydro',
   'QC_Complete': 'QC Complete',
   'RdyToShip': 'Ready To Ship',
   'OutsideService': 'Outside Service',
   'Ship_Paint': 'Ship To Paint',
   'Shipped': 'Shipped',
   'Packing_List_Paint': 'Paint Packing List',
   'Packing_List_No_First': 'First Packing List Number',
   'Packing_List_OutsideSvc': 'Outside Service Packing List',
   'Notes': 'Notes',
   'Billed': 'Billed Date',
   'Invoice_No': 'Invoice Number',
   'Invoice_Date': 'Invoice Date',
   'Yard_Loc': 'Yard Location',
   'RT_PCT': 'RT %',
   'PTMT_PCT': 'PT/MT %',
   'VI_PCT': 'VT %',
   'FAB_TOL': 'Fabrication Tolerance',
   'ShippingTicketID': 'Shipping Ticket ID',
   'PaintShippingTicketID': 'Paint Shipping Ticket ID',
   'OutsideSvcShippingTicketID': 'Outside Service Shipping Ticket ID',
   'Voided': 'Voided'
}

weld_column_mapping = {
    'WLD_ClientCode': 'Client Code', 
    'WLD_ControlNo': 'Spool', 
    'WLD_DiaInch': 'DiaInch', 
    'WLD_FitDate': 'Fit Date', 
    'WLD_FitterID': 'Fitter ID', 
    'WLD_FromHeatNo': 'From Heat No', 
    'WLD_FromMat': 'From Mat', 
    'WLD_Genre': 'Joint', 
    'WLD_ID': 'WLD_ID', 
    'WLD_Index': 'Weld Index', 
    'WLD_INPS1Date': 'QC 1 Date', 
    'WLD_INSP1': 'QC 1', 
    'WLD_INSP10': 'QC 10', 
    'WLD_INSP10Date': 'QC 10 Date', 
    'WLD_INSP2': 'QC 2', 
    'WLD_INSP2Date': 'QC 2 Date', 
    'WLD_INSP3': 'QC 3', 
    'WLD_INSP3Date': 'QC 3 Date', 
    'WLD_INSP4': 'QC 4', 
    'WLD_INSP4Date': 'QC 4 Date', 
    'WLD_INSP5': 'QC 5', 
    'WLD_INSP5Date': 'QC 5 Date', 
    'WLD_INSP6': 'QC 6', 
    'WLD_INSP6Date': 'QC 6 Date', 
    'WLD_INSP7Date': 'QC 7 Date', 
    'WLD_INSP8': 'QC 8', 
    'WLD_INSP8Date': 'QC 8 Date', 
    'WLD_INSP9': 'QC 9', 
    'WLD_INSP9Date': 'QC 9 Date', 
    'WLD_JobID': 'Job', 
    'WLD_LotNo': 'Lot No', 
    'WLD_MatGroup': 'MTRL Group', 
    'WLD_MSWeldCode': 'MS Weld Code', 
    'WLD_NSP7': 'QC 7', 
    'WLD_PassFail': 'ACC/REJ', 
    'WLD_Remark': 'Remark', 
    'WLD_Remark2': 'Remark2', 
    'WLD_Remark3': 'Remark3', 
    'WLD_Revision': 'Revision', 
    'WLD_RTPercent': 'RT Percent', 
    'WLD_SGroup': 'S Group', 
    'WLD_Size_I': 'Size', 
    'WLD_Size_M': 'Size(mm)', 
    'WLD_Spec': 'Pipe Spec', 
    'WLD_T1Label': 'T1 Label', 
    'WLD_T2Label': 'T2 Label', 
    'WLD_TFCN': 'TFCN', 
    'WLD_ToHeatNo': 'To Heat No', 
    'WLD_ToMat': 'To Mat', 
    'WLD_Tracer1CN': 'Tracer 1 CN', 
    'WLD_Tracer2CN': 'Tracer 2 CN', 
    'WLD_Traceraux': 'Traceraux', 
    'WLD_UserCode': 'User Code', 
    'WLD_Wall_I': 'SCH Desc.', 
    'WLD_Wall_M': 'Wall_M', 
    'WLD_WDescript': 'Joint Detail', 
    'WLD_WeldDate': 'Weld Date', 
    'WLD_Welder2ID': 'Stencil 2', 
    'WLD_WelderID': 'Stencil 1', 
    'WLD_WeldFrom': 'Weld From', 
    'WLD_WeldLabel': 'Weld Label', 
    'WLD_WeldProc': 'Weld Procedure', 
    'WLD_WeldTo': 'Weld To', 


    }